import { createHash } from 'node:crypto';
import makeWASocket,{DisconnectReason,useMultiFileAuthState,type WASocket} from '@whiskeysockets/baileys';
import qrcode from 'qrcode-terminal';
import { DispatchError,type WhatsAppSender } from './outbox.js';
export interface InboundMessage { phoneE164:string; providerMessageId:string; text:string; receivedAt:string; }
export type BaileysPairingState = { state:'starting'|'qr'|'connected'|'disconnected'|'error'; qrCode?:string|null; qrExpiresAt?:string|null; lastError?:string|null };
type OptOutHandler=(phoneE164:string)=>Promise<void>; type InboundHandler=(message:InboundMessage)=>Promise<void>; type PairingHandler=(state:BaileysPairingState)=>Promise<void>;
export class BaileysSender implements WhatsAppSender {
 private socket:WASocket|null=null;private connected=false;private starting:Promise<void>|null=null;private stopped=false;private reconnectTimer:NodeJS.Timeout|null=null;
 constructor(private readonly authDir:string,private readonly onOptOut?:OptOutHandler,private readonly onInbound?:InboundHandler,private readonly onPairingState?:PairingHandler){}
 isReady():boolean{return Boolean(this.socket&&this.connected&&!this.stopped);}
 async start():Promise<void>{if(this.starting)return this.starting;this.stopped=false;await this.report({state:'starting'});this.starting=this.connect().finally(()=>{this.starting=null;});return this.starting;}
 async send(phoneE164:string,body:string,idempotencyKey:string):Promise<{id:string}>{if(!this.isReady()||!this.socket)throw new DispatchError('whatsapp_not_connected',true);let jid:string;try{jid=toWhatsAppJid(phoneE164);}catch{throw new DispatchError('invalid_e164_phone',false);}const messageId=toProviderMessageId(idempotencyKey);try{const result=await this.socket.sendMessage(jid,{text:body},{messageId});const id=result?.key.id;if(!id)throw new DispatchError('provider_message_id_missing',false);return{id};}catch(error){if(error instanceof DispatchError)throw error;throw new DispatchError('provider_send_outcome_unknown',false);}}
 stop():void{this.stopped=true;this.connected=false;if(this.reconnectTimer)clearTimeout(this.reconnectTimer);this.reconnectTimer=null;this.socket?.end(undefined);this.socket=null;void this.report({state:'disconnected'});}
 private async connect():Promise<void>{if(this.stopped)return;const {state,saveCreds}=await useMultiFileAuthState(this.authDir);const socket=makeWASocket({auth:state,printQRInTerminal:false,markOnlineOnConnect:false,syncFullHistory:false});this.socket=socket;socket.ev.on('creds.update',saveCreds);socket.ev.on('messages.upsert',({messages})=>{for(const message of messages){if(message.key.fromMe)continue;const phoneE164=jidToE164(message.key.remoteJid);const text=extractText(message.message);const providerMessageId=message.key.id;const receivedAt=toReceivedAt(message.messageTimestamp);if(!phoneE164||!text||!providerMessageId)continue;if(this.onInbound)void this.onInbound({phoneE164,providerMessageId,text,receivedAt}).catch(error=>console.error('[whatsapp] falha ao registrar inbound',{contact:maskPhone(phoneE164),error:error instanceof Error?error.message:'unknown_error'}));if(this.onOptOut&&isOptOutText(text))void this.onOptOut(phoneE164).then(()=>console.log('[whatsapp] opt-out registrado',{contact:maskPhone(phoneE164)})).catch(error=>console.error('[whatsapp] falha ao registrar opt-out',{contact:maskPhone(phoneE164),error:error instanceof Error?error.message:'unknown_error'}));}});socket.ev.on('connection.update',(update)=>{if(update.qr){console.log('[whatsapp] QR disponível; escaneie no WhatsApp vinculado à Nora.');qrcode.generate(update.qr,{small:true});void this.report({state:'qr',qrCode:update.qr,qrExpiresAt:new Date(Date.now()+60_000).toISOString()});}if(update.connection==='open'){this.connected=true;console.log('[whatsapp] sessão conectada');void this.report({state:'connected'});}if(update.connection==='close'){this.connected=false;if(this.socket===socket)this.socket=null;const statusCode=extractStatusCode(update.lastDisconnect?.error);const loggedOut=statusCode===DisconnectReason.loggedOut;console.error('[whatsapp] conexão encerrada',{statusCode,loggedOut});void this.report({state:loggedOut?'disconnected':'error',lastError:loggedOut?'logged_out':`connection_closed_${statusCode??'unknown'}`});if(!this.stopped&&!loggedOut&&!this.reconnectTimer){this.reconnectTimer=setTimeout(()=>{this.reconnectTimer=null;void this.connect().catch(error=>{console.error('[whatsapp] reconexão falhou',error);void this.report({state:'error',lastError:error instanceof Error?error.message:'reconnect_failed'});});},5000);}}});}
 private async report(state:BaileysPairingState):Promise<void>{if(!this.onPairingState)return;try{await this.onPairingState(state);}catch(error){console.error('[whatsapp] falha ao registrar estado de pareamento',error instanceof Error?error.message:'unknown_error');}}
}
export function toWhatsAppJid(phoneE164:string):string{if(!/^\+[1-9]\d{7,14}$/.test(phoneE164))throw new Error('invalid_e164_phone');return `${phoneE164.slice(1)}@s.whatsapp.net`;}
export function toProviderMessageId(idempotencyKey:string):string{if(!idempotencyKey.trim())throw new Error('idempotency_key_required');return createHash('sha256').update(`nora-whatsapp:${idempotencyKey}`).digest('hex').slice(0,32).toUpperCase();}
export function isOptOutText(value:string):boolean{const normalized=value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');return new Set(['sair','pare','parar','stop','unsubscribe','remover meu contato','remova meu contato','nao quero receber mensagens','nao me envie mensagens','nao me contate','nao entre em contato','cancele as mensagens']).has(normalized);}
export function toReceivedAt(value:unknown):string{let seconds:number|null=null;if(typeof value==='number')seconds=value;else if(typeof value==='bigint')seconds=Number(value);else if(value&&typeof value==='object'&&'toNumber' in value&&typeof (value as {toNumber?:unknown}).toNumber==='function')seconds=(value as {toNumber:()=>number}).toNumber();if(!seconds||!Number.isFinite(seconds)||seconds<=0)return new Date().toISOString();const date=new Date(seconds*1000);return Number.isNaN(date.getTime())?new Date().toISOString():date.toISOString();}
function extractStatusCode(error:unknown):number|undefined{if(!error||typeof error!=='object')return undefined;const candidate=error as {output?:{statusCode?:number};statusCode?:number};return candidate.output?.statusCode??candidate.statusCode;}
function jidToE164(jid:string|null|undefined):string|null{if(!jid?.endsWith('@s.whatsapp.net'))return null;const digits=jid.slice(0,-'@s.whatsapp.net'.length).split(':')[0];if(!digits||!/^[1-9]\d{7,14}$/.test(digits))return null;return `+${digits}`;}
function extractText(message:{conversation?:string|null;extendedTextMessage?:{text?:string|null}|null}|null|undefined):string|null{return message?.conversation??message?.extendedTextMessage?.text??null;}
function maskPhone(phoneE164:string):string{return `***${phoneE164.slice(-4)}`;}
